name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: my-app/package-lock.json  # ✅ Point cache to correct path

    - name: Install dependencies
      run: npm ci
      working-directory: my-app  # ✅ Run npm commands in my-app/

    - name: Build project
      run: npm run build --if-present
      working-directory: my-app  # ✅ Run build inside my-app/

    - name: Run tests
      run: npm test
      working-directory: my-app  # ✅ Run tests inside my-app/
